export enum CardEffectType {
  PAY_TO_BANK = 'PAY_TO_BANK',
  PAY_TO_ALL_PLAYERS = 'PAY_TO_ALL_PLAYERS',
  PAY_PER_PROPERTY = 'PAY_PER_PROPERTY',
  RECEIVE_FROM_BANK = 'RECEIVE_FROM_BANK',
  RECEIVE_FROM_ALL_PLAYERS = 'RECEIVE_FROM_ALL_PLAYERS',
  GO_TO_JAIL = 'GO_TO_JAIL',
  GET_OUT_OF_JAIL = 'GET_OUT_OF_JAIL',
  MOVE_TO_BOX = 'MOVE_TO_BOX',
  MOVE_X_AMOUNT = 'MOVE_X_AMOUNT'
}
